# Generated by Django 5.2.5 on 2025-11-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                default="praveengupta6450@gmail.com", max_length=254
            ),
            preserve_default=False,
        ),
    ]
